if (NOT DEFINED FIXEDCOMPRESSION)
    set(FIXEDCOMPRESSION false)
endif ()
if (NOT DEFINED METADATABYTES)
    set(METADATABYTES 8)
endif ()
if (NOT DEFINED DEEPMETADATA)
    set(DEEPMETADATA false)
else()
    if (DEEPMETADATA AND FIXEDCOMPRESSION)
        message(FATAL_ERROR "Deep Metadata not supported with fixed compression")
    endif ()
    if (DEEPMETADATA AND NOT METADATABYTES EQUAL 8)
        message(FATAL_ERROR "Deep Metadata requires 8 byte Metadata")
    endif ()
endif ()
if (NOT DEFINED DEEPMETADATABYTES)
    set(DEEPMETADATABYTES 8)
else ()
    if (NOT DEEPMETADATA)
        message(FATAL_ERROR "Trying to set Deep Metadata size when none requested")
    endif ()
endif ()

if (NOT DEFINED ALLOC_SIZE_HOOK)
    set(ALLOC_SIZE_HOOK_ENABLED 0)
else ()
    set(ALLOC_SIZE_HOOK_ENABLED 1)
endif ()

if (NOT DEFINED ALLOC_HOOK)
    set(ALLOC_HOOK default_alloc_hook)
endif ()

if (NOT DEFINED RESIZE_HOOK)
    set(RESIZE_HOOK_ENABLED 0)
else ()
    set(RESIZE_HOOK_ENABLED 1)
endif ()

if (NOT DEFINED FREE_HOOK)
    set(FREE_HOOK_ENABLED 0)
else ()
    set(FREE_HOOK_ENABLED 1)
endif ()

configure_file(metapagetable.h.in metapagetable.h)
configure_file(linker-options.in linker-options)
